### ISSUE TITLE
似乎鸠棘鱼和鱼饵的对应关系错了

### ISSUE THREAD

**Issue by xinjunjie1** [HuYo-OS/Genshin_auto_fish#10]
在钓鸠棘鱼（如果我记错的话）的时候程序设定的对应鱼饵好像变成了果酿饵

**Comment by LittleMio** [comment]
![image](https://user-images.githubusercontent.com/94115384/166729136-2e0b1d88-5cfc-4e0b-9f4b-c8caa537f9c7.png)

0对应果酿饵；1对应赤糜饵；2对应蠕虫假饵，3则对应飞蝇假饵
并没有设置错误，主要还是数据集里关于棘鱼的图像比较少，从而导致训练出来的模型识别的结果有误差才选错鱼饵的

**Comment by DracheShiki** [comment]
是的，各种棘鱼识别都有问题。是否有更新的数据集？需要提供棘鱼图片吗？

**Comment by LittleMio** [comment]
> 是的，各种棘鱼识别都有问题。是否有更新的数据集？需要提供棘鱼图片吗？

<s>最近在咕咕咕</s>，如果你需要提供的话，可以打包好并上传给我，我会打好标签并进行训练的
### 注：截图尽量全屏，且包含鱼在内

**Comment by DracheShiki** [comment]
> 

https://drive.google.com/file/d/1nMOdBKOoDNHSAxwKKpiMgflCFzcNwRmu/view?usp=sharing

主要是赤魔王和棘鱼的特写。掺杂了一些其他鱼。辛苦了！

**Comment by LittleMio** [comment]
> > 
> 
> https://drive.google.com/file/d/1nMOdBKOoDNHSAxwKKpiMgflCFzcNwRmu/view?usp=sharing
> 
> 主要是赤魔王和棘鱼的特写。掺杂了一些其他鱼。辛苦了！

嗯嗯，图片我收到啦，现在正在训练
