### ISSUE TITLE
執行 python setup.py develop時報錯fatal error C1083: 無法開啟包含檔案: 'basetsd.h': No such file or directory

### ISSUE THREAD

**Issue by KobeRyanX** [HuYo-OS/Genshin_auto_fish#11]
(ysfish) C:\Users\s12da\Documents\Genshin_auto_fish>python setup.py develop
running develop
C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
writing yolox.egg-info\PKG-INFO
writing dependency_links to yolox.egg-info\dependency_links.txt
writing top-level names to yolox.egg-info\top_level.txt
C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:387: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'yolox.egg-info\SOURCES.txt'
writing manifest file 'yolox.egg-info\SOURCES.txt'
running build_ext
building 'yolox._C' extension
"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\s12da\Documents\Genshin_auto_fish\yolox\layers\csrc -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\TH -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\THC -IC:\Users\s12da\anaconda3\envs\ysfish\include -IC:\Users\s12da\anaconda3\envs\ysfish\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt" /EHsc /TpC:\Users\s12da\Documents\Genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.cpp /Fobuild\temp.win-amd64-3.7\Release\Users\s12da\Documents\Genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
cl : 命令列 warning D9002 : 忽略未知的選項 '-O3'
cocoeval.cpp
C:\Users\s12da\anaconda3\envs\ysfish\include\pyconfig.h(203): fatal error C1083: 無法開啟包含檔案: 'basetsd.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by LittleMio** [comment]
应该是Microsoft Visual Studio的问题，请确认你已正确安装，推荐安装Microsoft Visual Studio 2022

从 Windows 版邮件发送

发件人: KobeRyanX
发送时间: 2022年5月5日 17:16
收件人: HuYo-OS/Genshin_auto_fish
抄送: Subscribed
主题: [HuYo-OS/Genshin_auto_fish] 執行 python setup.py develop時報錯fatal error C1083: 無法開啟包含檔案: 'basetsd.h': No such file or directory (Issue #11)

(ysfish) C:\Users\s12da\Documents\Genshin_auto_fish>python setup.py develop
running develop
C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
EasyInstallDeprecationWarning,
C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
setuptools.SetuptoolsDeprecationWarning,
running egg_info
writing yolox.egg-info\PKG-INFO
writing dependency_links to yolox.egg-info\dependency_links.txt
writing top-level names to yolox.egg-info\top_level.txt
C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:387: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'yolox.egg-info\SOURCES.txt'
writing manifest file 'yolox.egg-info\SOURCES.txt'
running build_ext
building 'yolox._C' extension
"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\s12da\Documents\Genshin_auto_fish\yolox\layers\csrc -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\TH -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\THC -IC:\Users\s12da\anaconda3\envs\ysfish\include -IC:\Users\s12da\anaconda3\envs\ysfish\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt" /EHsc /TpC:\Users\s12da\Documents\Genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.cpp /Fobuild\temp.win-amd64-3.7\Release\Users\s12da\Documents\Genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
cl : 命令列 warning D9002 : 忽略未知的選項 '-O3'
cocoeval.cpp
C:\Users\s12da\anaconda3\envs\ysfish\include\pyconfig.h(203): fatal error C1083: 無法開啟包含檔案: 'basetsd.h': No such file or directory
error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe' failed with exit code 2

**Comment by KobeRyanX** [comment]
> 应该是Microsoft Visual Studio的问题，请确认你已正确安装，推荐安装Microsoft Visual Studio 2022 从 Windows 版邮件发送 

原來要裝2022嗎，我裝的是2019

**Comment by LittleMio** [comment]
> > 应该是Microsoft Visual Studio的问题，请确认你已正确安装，推荐安装Microsoft Visual Studio 2022 从 Windows 版邮件发送
> 
> 原來要裝2022嗎，我裝的是2019

旧版本的bug比较多

**Comment by KobeRyanX** [comment]
> > > 应该是Microsoft Visual Studio的问题，请确认你已正确安装，推荐安装Microsoft Visual Studio 2022 从 Windows 版邮件发送
> > 
> > 
> > 原來要裝2022嗎，我裝的是2019
> 
> 旧版本的bug比较多

裝完2022了 問題還是一樣
p.s. 我是win11

**Comment by LittleMio** [comment]
> > > > 应该是Microsoft Visual Studio的问题，请确认你已正确安装，推荐安装Microsoft Visual Studio 2022 从 Windows 版邮件发送
> > > 
> > > 
> > > 原來要裝2022嗎，我裝的是2019
> > 
> > 
> > 旧版本的bug比较多
> 
> 裝完2022了 問題還是一樣 p.s. 我是win11

可以截图一下你安装的组件列表吗

**Comment by KobeRyanX** [comment]
> 
anaconda的還是 pip list?

**Comment by LittleMio** [comment]
不，是Microsoft Visual Studio的组件列表

**Comment by LittleMio** [comment]
@KobeRyanX 这是我安装的组件和单个组件，你可以参考一下
![image](https://user-images.githubusercontent.com/94115384/166908260-0687cb07-414a-4c0e-aa1b-b59de6e7ab7c.png)
![image](https://user-images.githubusercontent.com/94115384/166908341-9dc1e7fb-6a42-4a7e-85e2-7b8fe4a8f1b8.png)
![image](https://user-images.githubusercontent.com/94115384/166908277-ce846c9a-55d1-4d57-a5ce-4628e4ed6219.png)

**Comment by LittleMio** [comment]
安装完成之后记得重启电脑

**Comment by KobeRyanX** [comment]
[[img]https://upload.cc/i1/2022/05/05/3ByMik.png[/img]
[img]https://upload.cc/i1/2022/05/05/uoLOTn.png[/img]
](url)

**Comment by KobeRyanX** [comment]
![1](https://user-images.githubusercontent.com/100058274/166909182-6d9559db-9a3a-495d-883c-fd119116111c.png)
![2](https://user-images.githubusercontent.com/100058274/166909188-14bb74a3-449e-421a-971c-ef9245125e95.png)
一個是2019 一個是2022

**Comment by LittleMio** [comment]
先对照我的看看还有那些缺失的，先安装，看看能不能解决

**Comment by LittleMio** [comment]
实在不行我可以用TeamViewer远程协助

**Comment by KobeRyanX** [comment]
> 先对照我的看看还有那些缺失的，先安装，看看能不能解决

還是失敗 算了放棄

**Comment by HuYo-OS** [comment]
> > 先对照我的看看还有那些缺失的，先安装，看看能不能解决
> 
> 還是失敗 算了放棄



> error: command 'C:\Program Files (x86)\Microsoft Visual

我似乎复现了你这个问题

**Comment by KobeRyanX** [comment]
對了我是win11 不知道有沒有影響

**Comment by LittleMio** [comment]
我也是Windows11 没有影响

从 Windows 版邮件发送

发件人: KobeRyanX
发送时间: 2022年5月6日 23:42
收件人: HuYo-OS/Genshin_auto_fish
抄送: HUYO-OS; Comment
主题: Re: [HuYo-OS/Genshin_auto_fish] 執行 python setup.py develop時報錯fatal error C1083: 無法開啟包含檔案: 'basetsd.h': No such file or directory (Issue #11)

對了我是win11 不知道有沒有影響

**Comment by LittleMio** [comment]
我也是Windows11 ，没有影响

从 Windows 版邮件发送

发件人: KobeRyanX
发送时间: 2022年5月6日 23:42
收件人: HuYo-OS/Genshin_auto_fish
抄送: HUYO-OS; Comment
主题: Re: [HuYo-OS/Genshin_auto_fish] 執行 python setup.py develop時報錯fatal error C1083: 無法開啟包含檔案: 'basetsd.h': No such file or directory (Issue #11)

對了我是win11 不知道有沒有影響
