### ISSUE TITLE
请问不会自动换鱼饵是什么问题？

### ISSUE THREAD

**Issue by mhtwcnm1** [HuYo-OS/Genshin_auto_fish#13]
请问不会自动换鱼饵是什么问题？

**Comment by LittleMio** [comment]
你好，可以提交一下录屏和日志输出吗

**Comment by mhtwcnm1** [comment]
不好意思，由于我自身原因，不知道日志输出在哪看。我就用回去[7eu7d7](https://github.com/7eu7d7)这个版本了


可以顺便问一下，他这个按r开始，可不可以加个暂停的功能呢？现在停止只能直接关闭，有点麻烦。
