### ISSUE TITLE
脱钩问题

### ISSUE THREAD

**Issue by Rein-Ou** [HuYo-OS/Genshin_auto_fish#15]
1920*1080独占全屏，但是鱼咬钩之后不不会自动收杆

**Comment by LittleMio** [comment]
> 1920*1080独占全屏，但是鱼咬钩之后不不会自动收杆

请问这种情况是每次都会出现吗
如果不是
有些地方的环境可能会对右下角的鱼钩图标造成干扰，从而造成不会自动收杆

**Comment by Rein-Ou** [comment]
是的，每次都出现，抛竿识别换鱼饵都是正常的，就收杆不收，手动提竿之后也不会进行收杆操作

**Comment by LittleMio** [comment]
> 是的，每次都出现，抛竿识别换鱼饵都是正常的，就收杆不收，手动提竿之后也不会进行收杆操作

那可以麻烦提交一下运行时的日志文件和录屏吗，我试着排查一下
