### ISSUE TITLE
用7eu7d7那边的pth文件是可行，但是用这里的会报下面的错误

### ISSUE THREAD

**Issue by Commander222** [HuYo-OS/Genshin_auto_fish#16]
小白不懂，大佬求教！Python版本3.8.4

![image](https://user-images.githubusercontent.com/16162700/178103528-b1727a9c-b00b-494c-9b13-1502a0923ff2.png)

**Comment by LittleMio** [comment]
![image](https://user-images.githubusercontent.com/94115384/178106815-ca192478-ce51-461f-8b98-1bda238c9ed5.png)
这个pth文件只适配我的项目，所以，你把我的pth文件拷贝到7eu7d7的项目下运行，当然会报错啦

**Comment by Commander222** [comment]
好吧，是我复制来复制去的时候，搞混了。。。
现在好了！
太谢谢啦~
