### ISSUE TITLE
报错，但不影响运行

### ISSUE THREAD

**Issue by Hetols** [HuYo-OS/Genshin_auto_fish#18]
报错内容：
Traceback (most recent call last):
  File "fisher\environment.py", line 144, in throw_rod
    key=lambda x: distance((x[2][0] + x[2][2]) / 2, (x[2][1] + x[2][3]) / 2, rod_cx,
ValueError: min() arg is an empty sequence

代码原文：
fish_info = min(list(filter(lambda x: x[0] == fish_type, obj_list)), key=lambda x: distance((x[2][0] + x[2][2]) / 2, (x[2][1] + x[2][3]) / 2, rod_cx, rod_cy))

**Comment by LittleMio** [comment]
抛竿过程中没有找到鱼都会报这个错误的，属于正常现象

**Comment by Hetols** [comment]
好的，感谢解答
