### ISSUE TITLE
readme中，安装PyTorch代码有问题

### ISSUE THREAD

**Issue by Subbtan** [HuYo-OS/Genshin_auto_fish#19]
说明中介绍的是以CUDA11.6.2为例安装PyTorch，但代码中为11.3版本CUD
![H 5FVNKW6{~{QHBV$D }BYT](https://user-images.githubusercontent.com/40822847/185022466-c7187c7f-c761-4fc3-966e-800d6d817a16.png)

**Comment by LittleMio** [comment]
其实吧，只要你的cuda和cudnn的版本匹配并且cuda高于代码中的规定版本就行，cuda会向下兼容pytorch的

**Comment by Subbtan** [comment]
我装的是CUDA11.6.0，按照11.3装PyTorch的话，会报错，装cu116就没问题
