### ISSUE TITLE
关于鱼饵切换

### ISSUE THREAD

**Issue by yuewu666** [HuYo-OS/Genshin_auto_fish#23]
发现实际测试中肺棘鱼（蓝色枪鱼）的诱饵经常选成果酿饵（黄球），应该选的是赤糜饵（红球）才能钓上鱼，从而陷入死循环

**Comment by yuewu666** [comment]
我自己找了一下，原来是改了的select_food函数那里type=cv2.TM_SQDIFF_NORMED方法没有选对，所以总是切换错误，算是给作者找了个小bug

**Comment by LittleMio** [comment]
> 我自己找了一下，原来是改了的select_food函数那里type=cv2.TM_SQDIFF_NORMED方法没有选对，所以总是切换错误，算是给作者找了个小bug

好的，感谢你的帮忙(*^ω^*)
