### ISSUE TITLE
鱼咬钩之后不能正常的点鼠标

### ISSUE THREAD

**Issue by Jaceyxy** [HuYo-OS/Genshin_auto_fish#4]
请问为什么有些时候鱼咬钩之后不能正常的点鼠标，那个力度的进度条完全不对

**Comment by HuYo-OS** [comment]
请问你是以1920*1080分辨率运行的游戏吗

**Comment by Jaceyxy** [comment]
是的，我的电脑时暗影精灵7，1920*1080的屏幕

**Comment by Jaceyxy** [comment]
![图片1](https://user-images.githubusercontent.com/54926038/159283008-00a1bbf0-bc75-47c9-882f-72dbae9abf3f.png)

**Comment by Jaceyxy** [comment]
![2022321235357](https://user-images.githubusercontent.com/54926038/159299917-0731ca57-9f6c-4a02-93ab-3c7c517270cc.png)
