### ISSUE TITLE
鱼饵选用好像有bug？

### ISSUE THREAD

**Issue by qq2473577621** [HuYo-OS/Genshin_auto_fish#5]
![5$3AVSKFE{WNU2RMD06$8)O](https://user-images.githubusercontent.com/87268494/161485515-95d35901-6598-4975-b3cd-72a0daad5c40.png)
如题如图 这种鱼应该选用红球球饵料 ai不清楚是模型识别错了还是饵料选择坐标有问题 会选成橙球球饵料
![6`D7AA8J(V6IKKMIK3R9O H](https://user-images.githubusercontent.com/87268494/161485813-3ed0055f-28cb-4437-b449-b522069c0ebf.png)

**Comment by HuYo-OS** [comment]
能把img_tmp文件夹下的所有图片打包发给我吗

**Comment by HuYo-OS** [comment]
已修复
