### ISSUE TITLE
python setup.py develop出错

### ISSUE THREAD

**Issue by Nomination-NRB** [HuYo-OS/Genshin_auto_fish#8]
(ysfish) C:\Users\76608\Genshin_auto_fish>python setup.py develop
running develop
E:\test\envs\ysfish\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
E:\test\envs\ysfish\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
creating yolox.egg-info
writing yolox.egg-info\PKG-INFO
writing dependency_links to yolox.egg-info\dependency_links.txt
writing top-level names to yolox.egg-info\top_level.txt
writing manifest file 'yolox.egg-info\SOURCES.txt'
E:\test\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:387: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'yolox.egg-info\SOURCES.txt'
writing manifest file 'yolox.egg-info\SOURCES.txt'
running build_ext
**E:\test\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:322: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。**
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'yolox._C' extension
creating build
creating build\temp.win-amd64-cpython-37
creating build\temp.win-amd64-cpython-37\Release
creating build\temp.win-amd64-cpython-37\Release\Users
creating build\temp.win-amd64-cpython-37\Release\Users\76608
creating build\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish
creating build\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish\yolox
creating build\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish\yolox\layers
creating build\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish\yolox\layers\csrc
creating build\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish\yolox\layers\csrc\cocoeval
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\76608\Genshin_auto_fish\yolox\layers\csrc -IE:\test\envs\ysfish\lib\site-packages\torch\include -IE:\test\envs\ysfish\lib\site-packages\torch\include\torch\csrc\api\include -IE:\test\envs\ysfish\lib\site-packages\torch\include\TH -IE:\test\envs\ysfish\lib\site-packages\torch\include\THC -IE:\test\envs\ysfish\include -IE:\test\envs\ysfish\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /TpC:\Users\76608\Genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.cpp /Fobuild\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
cl: 命令行 warning D9002 :忽略未知选项“-O3”
cocoeval.cpp
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\76608\Genshin_auto_fish\yolox\layers\csrc -IE:\test\envs\ysfish\lib\site-packages\torch\include -IE:\test\envs\ysfish\lib\site-packages\torch\include\torch\csrc\api\include -IE:\test\envs\ysfish\lib\site-packages\torch\include\TH -IE:\test\envs\ysfish\lib\site-packages\torch\include\THC -IE:\test\envs\ysfish\include -IE:\test\envs\ysfish\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /TpC:\Users\76608\Genshin_auto_fish\yolox\layers\csrc\vision.cpp /Fobuild\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish\yolox\layers\csrc\vision.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
cl: 命令行 warning D9002 :忽略未知选项“-O3”
vision.cpp
creating C:\Users\76608\Genshin_auto_fish\build\lib.win-amd64-cpython-37
creating C:\Users\76608\Genshin_auto_fish\build\lib.win-amd64-cpython-37\yolox
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:E:\test\envs\ysfish\lib\site-packages\torch\lib /LIBPATH:E:\test\envs\ysfish\libs /LIBPATH:E:\test\envs\ysfish /LIBPATH:E:\test\envs\ysfish\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit__C build\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.obj build\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish\yolox\layers\csrc\vision.obj /OUT:build\lib.win-amd64-cpython-37\yolox\_C.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish\yolox\layers\csrc\cocoeval\_C.cp37-win_amd64.lib
  正在创建库 build\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish\yolox\layers\csrc\cocoeval\_C.cp37-win_amd64.lib 和对象 build\temp.win-amd64-cpython-37\Release\Users\76608\Genshin_auto_fish\yolox\layers\csrc\cocoeval\_C.cp37-win_amd64.exp
**正在生成代码
已完成代码的生成**
copying build\lib.win-amd64-cpython-37\yolox\_C.cp37-win_amd64.pyd -> yolox
Creating e:\test\envs\ysfish\lib\site-packages\yolox.egg-link (link to .)
Adding yolox 0.1.0 to easy-install.pth file

Installed c:\users\76608\genshin_auto_fish
Processing dependencies for yolox==0.1.0
Finished processing dependencies for yolox==0.1.0

请问，加粗部分出错后，仍然显示代码生成完毕，会影响后序操作吗，我后面依照教程来弄，直接error了

**Comment by LittleMio** [comment]
pip list看看是否有yolox，如果有就不影响

**Comment by Nomination-NRB** [comment]
> pip list看看是否有yolox，如果有就不影响

此问题已解决，感谢
